# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Arvin's Blog
author:
  name: Arvin
  email: wangpfitta@163.com

description: >- # this means to ignore newlines until "baseurl:"
  “若无必要，勿增实体”（Non sunt multiplicanda entia sine necessitate）

# Build settings
show_excerpts: true

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 #- about.md

minima:
  date_format: "%b %-d, %Y"
  #skin: dark
  social_links:
    github: ittarvin

theme: minima
markdown: kramdown

kramdown:
  header_offset: 2
  input: GFM
  math_engine: mathjax
  syntax_highlighter: coderay
  syntax_highlighter_opts:
   # line_numbers: nil
    bold_every: 10

collections_dir: page_collections

collections:
  posts:
    output: true
  os:
    output: true
  data_struct:
      output: true

#Pagination does not work from within Markdown files from your Jekyll site. Pagination works when called from within the HTML file, named index.html,
#which optionally may reside in and produce pagination from within a subdirectory,
#via the paginate_path configuration value.
#paginate: 5
#paginate_path: "_posts/page:num/"


plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-avatar



# remote_theme: ngzhio/jekyll-theme-hamilton

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

feed:
  categories:
    - news
    - updates

jekyll-archives:
  # year, month, day, categories, tags
  enabled: all
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'