# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Arvin's WiKi
email: wangpfitta@163.com
description: >- # this means to ignore newlines until "baseurl:"
  “若无必要，勿增实体”（Non sunt multiplicanda entia sine necessitate）
#  "探索者都需要清楚三件事：现在的位置，目标，以及通向目标的道路。".
#  “世界上只有两样东西是值得我们深深景仰的，一个是我们头上灿烂的星空，一个是我们内心崇高的道德法则。”.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  ittarvin
# Build settings
#theme: jekyll-theme-simplex
theme: minima
#theme: just-the-docs
#theme: jekyll-agency
#theme: monophase
#theme: jekyll-theme-chirpy
#markdown: kramdown
kramdown:
  #input: kramdown-parser-gfm
  math_engine: mathjax
  extensions:
    - autolink
    - footnotes
    - smart
  #gfm_quirks: [paragraph_end]
  syntax_highlighter: coderay
  syntax_highlighter_opts:
   # line_numbers: nil
    bold_every: 10

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links
#  - jekyll-remote-theme

# remote_theme: ngzhio/jekyll-theme-hamilton

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

#  The built-in skins include daylight, midnight, sunrise, and sunset
# skin: sunrise
# paginate: 5
# permalink: pretty